export const DEFAULT_PAGE_SIZE = 5
export const DEFAULT_GROUP_SIZE = 1

export const SAMPLE_DATA_EMPTY = []

export const SAMPLE_DATA_10 = [
  {
    id: 1,
    first_name: 'Carmen',
    last_name: 'Zanardii',
    email: 'czanardii0@cargocollective.com',
    gender: 'Male',
    car: 'Cadillac',
    city: 'Laborie',
  },
  {
    id: 2,
    first_name: 'Meghann',
    last_name: 'Overbury',
    email: 'moverbury1@bbb.org',
    gender: 'Female',
    car: 'Kia',
    city: 'Saint-Louis',
  },
  {
    id: 3,
    first_name: 'Joya',
    last_name: 'Clayal',
    email: 'jclayal2@flickr.com',
    gender: 'Male',
    car: 'Buick',
    city: 'Ban Phai',
  },
  {
    id: 4,
    first_name: 'Carlye',
    last_name: 'Sarchwell',
    email: 'csarchwell3@moonfruit.com',
    gender: 'Genderqueer',
    car: 'Nissan',
    city: 'Steinkjer',
  },
  {
    id: 5,
    first_name: 'Dorris',
    last_name: 'Spickett',
    email: 'dspickett4@lulu.com',
    gender: 'Genderqueer',
    car: 'Suzuki',
    city: 'Ivanava',
  },
  {
    id: 6,
    first_name: 'Christalle',
    last_name: 'Spragg',
    email: 'cspragg5@theglobeandmail.com',
    gender: 'Genderqueer',
    car: 'Honda',
    city: 'Kelīshād va Sūdarjān',
  },
  {
    id: 7,
    first_name: 'Page',
    last_name: 'Herrero',
    email: 'pherrero6@comsenz.com',
    gender: 'Bigender',
    car: 'Isuzu',
    city: 'Mikuni',
  },
  {
    id: 8,
    first_name: 'Amil',
    last_name: 'Smale',
    email: 'asmale7@unesco.org',
    gender: 'Female',
    car: 'Lotus',
    city: 'Pasto',
  },
  {
    id: 9,
    first_name: 'Kaylyn',
    last_name: 'Mountstephen',
    email: 'kmountstephen8@paginegialle.it',
    gender: 'Bigender',
    car: 'GMC',
    city: 'Tadjoura',
  },
  {
    id: 10,
    first_name: 'Dalis',
    last_name: 'Hardwick',
    email: 'dhardwick9@bravesites.com',
    gender: 'Genderqueer',
    car: 'Pontiac',
    city: 'Albania',
  },
]

export const SAMPLE_DATA_100 = [
  {
    id: 1,
    first_name: 'Carmen',
    last_name: 'Zanardii',
    email: 'czanardii0@cargocollective.com',
    gender: 'Male',
    car: 'Cadillac',
    city: 'Laborie',
  },
  {
    id: 2,
    first_name: 'Meghann',
    last_name: 'Overbury',
    email: 'moverbury1@bbb.org',
    gender: 'Female',
    car: 'Kia',
    city: 'Saint-Louis',
  },
  {
    id: 3,
    first_name: 'Joya',
    last_name: 'Clayal',
    email: 'jclayal2@flickr.com',
    gender: 'Male',
    car: 'Buick',
    city: 'Ban Phai',
  },
  {
    id: 4,
    first_name: 'Carlye',
    last_name: 'Sarchwell',
    email: 'csarchwell3@moonfruit.com',
    gender: 'Genderqueer',
    car: 'Nissan',
    city: 'Steinkjer',
  },
  {
    id: 5,
    first_name: 'Dorris',
    last_name: 'Spickett',
    email: 'dspickett4@lulu.com',
    gender: 'Genderqueer',
    car: 'Suzuki',
    city: 'Ivanava',
  },
  {
    id: 6,
    first_name: 'Christalle',
    last_name: 'Spragg',
    email: 'cspragg5@theglobeandmail.com',
    gender: 'Genderqueer',
    car: 'Honda',
    city: 'Kelīshād va Sūdarjān',
  },
  {
    id: 7,
    first_name: 'Page',
    last_name: 'Herrero',
    email: 'pherrero6@comsenz.com',
    gender: 'Bigender',
    car: 'Isuzu',
    city: 'Mikuni',
  },
  {
    id: 8,
    first_name: 'Amil',
    last_name: 'Smale',
    email: 'asmale7@unesco.org',
    gender: 'Female',
    car: 'Lotus',
    city: 'Pasto',
  },
  {
    id: 9,
    first_name: 'Kaylyn',
    last_name: 'Mountstephen',
    email: 'kmountstephen8@paginegialle.it',
    gender: 'Bigender',
    car: 'GMC',
    city: 'Tadjoura',
  },
  {
    id: 10,
    first_name: 'Dalis',
    last_name: 'Hardwick',
    email: 'dhardwick9@bravesites.com',
    gender: 'Genderqueer',
    car: 'Pontiac',
    city: 'Albania',
  },
  {
    id: 11,
    first_name: 'Georas',
    last_name: 'Saltmarshe',
    email: 'gsaltmarshea@noaa.gov',
    gender: 'Bigender',
    car: 'Ford',
    city: 'Poja Nae',
  },
  {
    id: 12,
    first_name: 'Mireielle',
    last_name: 'Klezmski',
    email: 'mklezmskib@abc.net.au',
    gender: 'Male',
    car: 'Dodge',
    city: 'Rawaglagah',
  },
  {
    id: 13,
    first_name: 'Ronny',
    last_name: 'Tamsett',
    email: 'rtamsettc@etsy.com',
    gender: 'Bigender',
    car: 'Pontiac',
    city: 'Kaeng Khro',
  },
  {
    id: 14,
    first_name: 'Lynde',
    last_name: 'Nansom',
    email: 'lnansomd@usatoday.com',
    gender: 'Genderqueer',
    car: 'Ford',
    city: 'Dadong',
  },
  {
    id: 15,
    first_name: 'Marice',
    last_name: 'Antao',
    email: 'mantaoe@geocities.com',
    gender: 'Female',
    car: 'Ford',
    city: 'Stebnyk',
  },
  {
    id: 16,
    first_name: 'Charyl',
    last_name: 'Whittock',
    email: 'cwhittockf@adobe.com',
    gender: 'Agender',
    car: 'Buick',
    city: 'Puncakbaru',
  },
  {
    id: 17,
    first_name: 'Levin',
    last_name: 'Kubach',
    email: 'lkubachg@seattletimes.com',
    gender: 'Bigender',
    car: 'Kia',
    city: 'Tewulike',
  },
  {
    id: 18,
    first_name: 'Anthe',
    last_name: 'Morecombe',
    email: 'amorecombeh@sciencedirect.com',
    gender: 'Bigender',
    car: 'Volkswagen',
    city: 'Gandra',
  },
  {
    id: 19,
    first_name: 'Torry',
    last_name: 'Daly',
    email: 'tdalyi@quantcast.com',
    gender: 'Genderqueer',
    car: 'Volvo',
    city: 'Seixo da Beira',
  },
  {
    id: 20,
    first_name: 'Bobbe',
    last_name: 'Opdenort',
    email: 'bopdenortj@slashdot.org',
    gender: 'Non-binary',
    car: 'Dodge',
    city: 'Fengyang',
  },
  {
    id: 21,
    first_name: 'Ambur',
    last_name: 'Villaron',
    email: 'avillaronk@disqus.com',
    gender: 'Female',
    car: 'Audi',
    city: 'Port-Gentil',
  },
  {
    id: 22,
    first_name: 'Rockey',
    last_name: 'Restorick',
    email: 'rrestorickl@imageshack.us',
    gender: 'Non-binary',
    car: 'Mercedes-Benz',
    city: 'Stadtbredimus',
  },
  {
    id: 23,
    first_name: 'Nevile',
    last_name: 'Klimpke',
    email: 'nklimpkem@mapquest.com',
    gender: 'Polygender',
    car: 'Mitsubishi',
    city: 'Calabugao',
  },
  {
    id: 24,
    first_name: 'Perrine',
    last_name: 'Hillock',
    email: 'phillockn@free.fr',
    gender: 'Genderqueer',
    car: 'Infiniti',
    city: 'Tchintabaraden',
  },
  {
    id: 25,
    first_name: 'Skip',
    last_name: 'Mollitt',
    email: 'smollitto@google.com.hk',
    gender: 'Genderqueer',
    car: 'Mitsubishi',
    city: 'Pilar',
  },
  {
    id: 26,
    first_name: 'Sherye',
    last_name: 'Flewan',
    email: 'sflewanp@oracle.com',
    gender: 'Polygender',
    car: 'Audi',
    city: 'Eaton',
  },
  {
    id: 27,
    first_name: 'Mortimer',
    last_name: 'Witherby',
    email: 'mwitherbyq@wufoo.com',
    gender: 'Genderfluid',
    car: 'Plymouth',
    city: 'Mogadishu',
  },
  {
    id: 28,
    first_name: 'Susana',
    last_name: 'Slingsby',
    email: 'sslingsbyr@ning.com',
    gender: 'Genderfluid',
    car: 'Mazda',
    city: 'Sāqayn',
  },
  {
    id: 29,
    first_name: 'Stevena',
    last_name: 'Reinard',
    email: 'sreinards@blogger.com',
    gender: 'Bigender',
    car: 'Dodge',
    city: 'Nishor',
  },
  {
    id: 30,
    first_name: 'Alisa',
    last_name: 'Wroe',
    email: 'awroet@marketwatch.com',
    gender: 'Male',
    car: 'Toyota',
    city: 'Suvorov',
  },
  {
    id: 31,
    first_name: 'Kristel',
    last_name: 'Rewan',
    email: 'krewanu@smh.com.au',
    gender: 'Agender',
    car: 'Subaru',
    city: 'Liandu',
  },
  {
    id: 32,
    first_name: 'Guinna',
    last_name: 'Lumb',
    email: 'glumbv@army.mil',
    gender: 'Polygender',
    car: 'Ford',
    city: 'Senlis',
  },
  {
    id: 33,
    first_name: 'Sebastiano',
    last_name: 'Normanton',
    email: 'snormantonw@infoseek.co.jp',
    gender: 'Agender',
    car: 'Mercedes-Benz',
    city: 'Banjar Bias',
  },
  {
    id: 34,
    first_name: 'Carmela',
    last_name: 'Sherman',
    email: 'cshermanx@thetimes.co.uk',
    gender: 'Agender',
    car: 'Porsche',
    city: 'Sindangbarang',
  },
  {
    id: 35,
    first_name: 'Jilleen',
    last_name: 'Acedo',
    email: 'jacedoy@symantec.com',
    gender: 'Male',
    car: 'Land Rover',
    city: 'Leye',
  },
  {
    id: 36,
    first_name: 'Donni',
    last_name: 'Neljes',
    email: 'dneljesz@usda.gov',
    gender: 'Genderfluid',
    car: 'Volkswagen',
    city: 'Jazovo',
  },
  {
    id: 37,
    first_name: 'Ephraim',
    last_name: 'Monahan',
    email: 'emonahan10@pen.io',
    gender: 'Bigender',
    car: 'GMC',
    city: 'Monte Novo',
  },
  {
    id: 38,
    first_name: 'Nolana',
    last_name: 'Daley',
    email: 'ndaley11@indiegogo.com',
    gender: 'Genderfluid',
    car: 'Rolls-Royce',
    city: 'Changle',
  },
  {
    id: 39,
    first_name: 'Quintus',
    last_name: 'Conws',
    email: 'qconws12@jiathis.com',
    gender: 'Non-binary',
    car: 'Jeep',
    city: 'Bantardawa',
  },
  {
    id: 40,
    first_name: 'Skye',
    last_name: 'Ritchman',
    email: 'sritchman13@slashdot.org',
    gender: 'Female',
    car: 'Mitsubishi',
    city: 'Araras',
  },
  {
    id: 41,
    first_name: 'Karyl',
    last_name: 'Perview',
    email: 'kperview14@discovery.com',
    gender: 'Genderfluid',
    car: 'Chrysler',
    city: 'Bagé',
  },
  {
    id: 42,
    first_name: 'Vito',
    last_name: 'Stormont',
    email: 'vstormont15@netscape.com',
    gender: 'Non-binary',
    car: 'Ford',
    city: 'Leeuwarden',
  },
  {
    id: 43,
    first_name: 'Marianna',
    last_name: 'Checo',
    email: 'mcheco16@hc360.com',
    gender: 'Genderfluid',
    car: 'Cadillac',
    city: 'Lubowidz',
  },
  {
    id: 44,
    first_name: 'Jerrilee',
    last_name: 'Savidge',
    email: 'jsavidge17@prweb.com',
    gender: 'Female',
    car: 'Subaru',
    city: "Villeneuve-d'Ascq",
  },
  {
    id: 45,
    first_name: 'Hasty',
    last_name: 'Easter',
    email: 'heaster18@ocn.ne.jp',
    gender: 'Genderfluid',
    car: 'BMW',
    city: 'Mamburao',
  },
  {
    id: 46,
    first_name: 'Margo',
    last_name: 'Theaker',
    email: 'mtheaker19@facebook.com',
    gender: 'Genderqueer',
    car: 'Chrysler',
    city: 'Rychtal',
  },
  {
    id: 47,
    first_name: 'Fan',
    last_name: 'Kilfeder',
    email: 'fkilfeder1a@sitemeter.com',
    gender: 'Genderqueer',
    car: 'BMW',
    city: 'Peski',
  },
  {
    id: 48,
    first_name: 'Shelba',
    last_name: 'Bacchus',
    email: 'sbacchus1b@bloomberg.com',
    gender: 'Bigender',
    car: 'Oldsmobile',
    city: 'Chunghwa',
  },
  {
    id: 49,
    first_name: 'Bobbi',
    last_name: 'Denisot',
    email: 'bdenisot1c@yahoo.com',
    gender: 'Bigender',
    car: 'Cadillac',
    city: 'Tange Zhen',
  },
  {
    id: 50,
    first_name: 'Norris',
    last_name: 'Mottershead',
    email: 'nmottershead1d@gizmodo.com',
    gender: 'Genderqueer',
    car: 'Mazda',
    city: 'Port Saint Lucie',
  },
  {
    id: 51,
    first_name: 'Dermot',
    last_name: 'Allbrook',
    email: 'dallbrook1e@drupal.org',
    gender: 'Genderqueer',
    car: 'Suzuki',
    city: 'Tongchuan',
  },
  {
    id: 52,
    first_name: 'Suzi',
    last_name: 'Gennings',
    email: 'sgennings1f@slideshare.net',
    gender: 'Genderqueer',
    car: 'Pontiac',
    city: 'Kopashnovo',
  },
  {
    id: 53,
    first_name: 'Susi',
    last_name: 'Cornew',
    email: 'scornew1g@scientificamerican.com',
    gender: 'Male',
    car: 'Pontiac',
    city: 'Kivijärvi',
  },
  {
    id: 54,
    first_name: 'Lanna',
    last_name: 'Abrahamsson',
    email: 'labrahamsson1h@disqus.com',
    gender: 'Non-binary',
    car: 'BMW',
    city: 'Lille',
  },
  {
    id: 55,
    first_name: 'Marquita',
    last_name: 'Fishenden',
    email: 'mfishenden1i@linkedin.com',
    gender: 'Female',
    car: 'Toyota',
    city: 'Oklahoma City',
  },
  {
    id: 56,
    first_name: 'Gunilla',
    last_name: 'Sier',
    email: 'gsier1j@earthlink.net',
    gender: 'Genderfluid',
    car: 'Chevrolet',
    city: 'Bagalangit',
  },
  {
    id: 57,
    first_name: 'Roanna',
    last_name: 'Kellart',
    email: 'rkellart1k@ucoz.com',
    gender: 'Non-binary',
    car: 'Chevrolet',
    city: 'Qulaybīyah',
  },
  {
    id: 58,
    first_name: 'Darb',
    last_name: 'Burridge',
    email: 'dburridge1l@123-reg.co.uk',
    gender: 'Bigender',
    car: 'Lincoln',
    city: 'Rochester',
  },
  {
    id: 59,
    first_name: 'Jefferson',
    last_name: 'Volante',
    email: 'jvolante1m@ask.com',
    gender: 'Genderfluid',
    car: 'Dodge',
    city: 'Além do Rio',
  },
  {
    id: 60,
    first_name: 'Willey',
    last_name: 'Dussy',
    email: 'wdussy1n@altervista.org',
    gender: 'Female',
    car: 'Audi',
    city: 'Orlovskiy',
  },
  {
    id: 61,
    first_name: 'Luciano',
    last_name: 'Rawlingson',
    email: 'lrawlingson1o@irs.gov',
    gender: 'Genderqueer',
    car: 'Mercury',
    city: 'Bokhan',
  },
  {
    id: 62,
    first_name: 'Kira',
    last_name: 'Ibbs',
    email: 'kibbs1p@myspace.com',
    gender: 'Female',
    car: 'Bentley',
    city: 'Echarate',
  },
  {
    id: 63,
    first_name: 'Wilhelmina',
    last_name: 'Dyneley',
    email: 'wdyneley1q@blogtalkradio.com',
    gender: 'Genderqueer',
    car: 'Cadillac',
    city: 'Bacalan',
  },
  {
    id: 64,
    first_name: 'Marlowe',
    last_name: 'Barkworth',
    email: 'mbarkworth1r@live.com',
    gender: 'Female',
    car: 'Mitsubishi',
    city: 'Huaccana',
  },
  {
    id: 65,
    first_name: 'Dante',
    last_name: 'Pahlsson',
    email: 'dpahlsson1s@mashable.com',
    gender: 'Genderfluid',
    car: 'Mitsubishi',
    city: 'Zhongshu',
  },
  {
    id: 66,
    first_name: 'Sunshine',
    last_name: 'Hargrave',
    email: 'shargrave1t@fotki.com',
    gender: 'Genderqueer',
    car: 'Hyundai',
    city: 'Jadów',
  },
  {
    id: 67,
    first_name: 'Nita',
    last_name: 'Grundey',
    email: 'ngrundey1u@rediff.com',
    gender: 'Agender',
    car: 'Hyundai',
    city: 'Shiyu',
  },
  {
    id: 68,
    first_name: 'Humfried',
    last_name: 'Lorenzetti',
    email: 'hlorenzetti1v@diigo.com',
    gender: 'Genderfluid',
    car: 'Mitsubishi',
    city: 'Guangfu',
  },
  {
    id: 69,
    first_name: 'Robinet',
    last_name: 'Fullerd',
    email: 'rfullerd1w@phoca.cz',
    gender: 'Genderfluid',
    car: 'Volvo',
    city: 'Pansoy',
  },
  {
    id: 70,
    first_name: 'Crichton',
    last_name: 'Bremner',
    email: 'cbremner1x@gizmodo.com',
    gender: 'Male',
    car: 'Land Rover',
    city: 'Wendengying',
  },
  {
    id: 71,
    first_name: 'Mathe',
    last_name: 'Gittens',
    email: 'mgittens1y@latimes.com',
    gender: 'Genderqueer',
    car: 'Hyundai',
    city: 'Waegwan',
  },
  {
    id: 72,
    first_name: 'Quintilla',
    last_name: 'Headly',
    email: 'qheadly1z@blogs.com',
    gender: 'Genderfluid',
    car: 'Mercury',
    city: 'Kasreman',
  },
  {
    id: 73,
    first_name: 'Karla',
    last_name: 'Escale',
    email: 'kescale20@tinyurl.com',
    gender: 'Polygender',
    car: 'Chevrolet',
    city: 'Formosa',
  },
  {
    id: 74,
    first_name: 'Gwenora',
    last_name: 'Huggins',
    email: 'ghuggins21@ucoz.com',
    gender: 'Female',
    car: 'Eagle',
    city: 'Issy-les-Moulineaux',
  },
  {
    id: 75,
    first_name: 'Kermy',
    last_name: 'Wolffers',
    email: 'kwolffers22@slate.com',
    gender: 'Genderqueer',
    car: 'Chevrolet',
    city: 'Foluo',
  },
  {
    id: 76,
    first_name: 'Avery',
    last_name: 'Reekie',
    email: 'areekie23@gnu.org',
    gender: 'Non-binary',
    car: 'Ford',
    city: 'Santos Evos',
  },
  {
    id: 77,
    first_name: 'Carr',
    last_name: 'Sprigg',
    email: 'csprigg24@fc2.com',
    gender: 'Male',
    car: 'MINI',
    city: 'Mariatana',
  },
  {
    id: 78,
    first_name: 'Lizzy',
    last_name: 'Daspar',
    email: 'ldaspar25@sphinn.com',
    gender: 'Male',
    car: 'GMC',
    city: 'Al Hufūf',
  },
  {
    id: 79,
    first_name: 'Katrinka',
    last_name: 'Tunna',
    email: 'ktunna26@taobao.com',
    gender: 'Genderfluid',
    car: 'Volkswagen',
    city: 'Laotai',
  },
  {
    id: 80,
    first_name: 'Bee',
    last_name: 'Telford',
    email: 'btelford27@google.cn',
    gender: 'Agender',
    car: 'Alfa Romeo',
    city: 'Cabodiongan',
  },
  {
    id: 81,
    first_name: 'Shelagh',
    last_name: 'Saywell',
    email: 'ssaywell28@sciencedaily.com',
    gender: 'Genderfluid',
    car: 'Audi',
    city: 'Vilnius',
  },
  {
    id: 82,
    first_name: 'Rudolph',
    last_name: 'Staig',
    email: 'rstaig29@instagram.com',
    gender: 'Genderqueer',
    car: 'Audi',
    city: 'Mantalongon',
  },
  {
    id: 83,
    first_name: 'Devonne',
    last_name: 'Antalffy',
    email: 'dantalffy2a@moonfruit.com',
    gender: 'Non-binary',
    car: 'Chevrolet',
    city: 'Lugo',
  },
  {
    id: 84,
    first_name: 'Lissa',
    last_name: 'Castellani',
    email: 'lcastellani2b@imageshack.us',
    gender: 'Genderfluid',
    car: 'Mitsubishi',
    city: 'Koloniya Zastav’ye',
  },
  {
    id: 85,
    first_name: 'Isabeau',
    last_name: 'Dudden',
    email: 'idudden2c@addtoany.com',
    gender: 'Male',
    car: 'Mitsubishi',
    city: 'Thành Phố Hà Giang',
  },
  {
    id: 86,
    first_name: 'Tammie',
    last_name: 'Gouck',
    email: 'tgouck2d@vinaora.com',
    gender: 'Genderqueer',
    car: 'Buick',
    city: 'Pärnu-Jaagupi',
  },
  {
    id: 87,
    first_name: 'Doralia',
    last_name: 'Propper',
    email: 'dpropper2e@paypal.com',
    gender: 'Bigender',
    car: 'Chevrolet',
    city: 'Helsingborg',
  },
  {
    id: 88,
    first_name: 'Laurence',
    last_name: 'Cotterel',
    email: 'lcotterel2f@opensource.org',
    gender: 'Agender',
    car: 'Chevrolet',
    city: 'Vale de Mendiz',
  },
  {
    id: 89,
    first_name: 'Clementina',
    last_name: 'Macallam',
    email: 'cmacallam2g@cyberchimps.com',
    gender: 'Bigender',
    car: 'Porsche',
    city: 'Dajin',
  },
  {
    id: 90,
    first_name: 'Marcellus',
    last_name: 'Soame',
    email: 'msoame2h@icio.us',
    gender: 'Bigender',
    car: 'Nissan',
    city: 'Alor Setar',
  },
  {
    id: 91,
    first_name: 'Ed',
    last_name: 'Monnelly',
    email: 'emonnelly2i@ezinearticles.com',
    gender: 'Genderqueer',
    car: 'Dodge',
    city: 'Ruše',
  },
  {
    id: 92,
    first_name: 'Cornela',
    last_name: 'Meuse',
    email: 'cmeuse2j@xrea.com',
    gender: 'Bigender',
    car: 'Mitsubishi',
    city: 'Bijaepasu',
  },
  {
    id: 93,
    first_name: 'Blaine',
    last_name: 'Phippard',
    email: 'bphippard2k@google.com.au',
    gender: 'Male',
    car: 'Toyota',
    city: 'Aipe',
  },
  {
    id: 94,
    first_name: 'Fernande',
    last_name: 'Orniz',
    email: 'forniz2l@yelp.com',
    gender: 'Male',
    car: 'BMW',
    city: 'Thị Trấn Hát Lót',
  },
  {
    id: 95,
    first_name: 'Melany',
    last_name: "O'Lenane",
    email: 'molenane2m@ebay.co.uk',
    gender: 'Non-binary',
    car: 'Honda',
    city: 'Paso de Carrasco',
  },
  {
    id: 96,
    first_name: 'Netty',
    last_name: 'Saffell',
    email: 'nsaffell2n@sogou.com',
    gender: 'Polygender',
    car: 'Porsche',
    city: 'Balitoc',
  },
  {
    id: 97,
    first_name: 'Maxwell',
    last_name: 'Gallie',
    email: 'mgallie2o@reference.com',
    gender: 'Genderfluid',
    car: 'Mercury',
    city: 'Thionville',
  },
  {
    id: 98,
    first_name: 'Roanne',
    last_name: 'Cuming',
    email: 'rcuming2p@biblegateway.com',
    gender: 'Agender',
    car: 'BMW',
    city: 'Constantia',
  },
  {
    id: 99,
    first_name: 'Caralie',
    last_name: 'Bushell',
    email: 'cbushell2q@desdev.cn',
    gender: 'Agender',
    car: 'Porsche',
    city: 'Gur’yevsk',
  },
  {
    id: 100,
    first_name: 'Remus',
    last_name: 'Trevarthen',
    email: 'rtrevarthen2r@thetimes.co.uk',
    gender: 'Genderqueer',
    car: 'Land Rover',
    city: 'Novyy Starodub',
  },
]

export const SAMPLE_COLUMNS_TEXT = [
  'id',
  'first_name',
  'last_name',
  'email',
  'gender',
  'car',
  'city',
]

export const SAMPLE_COLUMNS_SORTABLE = [
  'id',
  { name: 'first_name', sortable: true },
  { name: 'last_name', sortable: true },
  { name: 'email', sortable: true },
  { name: 'gender', sortable: true, filterable: true },
  { name: 'car', sortable: true, filterable: true },
  { name: 'city', filterable: true },
]

export const SAMPLE_COLUMNS_WRONG_COUNT = [
  'id',
  'first_name',
  'last_name',
  'gender',
  'car',
  'city',
]

export const SAMPLE_COLUMNS_WRONG_ORDER = [
  'id',
  'first_name',
  'last_name',
  'gender',
  'email',
  'car',
  'city',
]
